/* eslint-disable @typescript-eslint/no-unsafe-argument */
import * as fs from "fs";
import * as path from "path";

(async () => {
	const res = await fetch("https://api.bybit.com/v5/market/instruments-info?category=linear");
	const data = await res.json();

	if (data.retCode !== 0) {
		throw new Error(`Bybit API Error: ${data.retMsg}`);
	}

	// Filter for USDT perpetual contracts
	const usdtSymbols = data.result?.list?.filter(
		(s: any) => s.quoteCoin === "USDT" && s.contractType === "LinearPerpetual"
	);

	const bybitRules = usdtSymbols.map((s: any) => ({
		pair: s.symbol,
		baseAsset: s.baseCoin,
		quoteCurrency: s.quoteCoin,
		minQuantity: parseFloat(s.lotSizeFilter?.minOrderQty || "0"),
		stepSize: parseFloat(s.lotSizeFilter?.qtyStep || "0"),
		minNotional: parseFloat(s.lotSizeFilter?.minNotionalValue || "0"),
	}));

	// Create TypeScript file content
	const tsContent = `// Auto-generated Bybit futures trading rules
export const bybitFuturesRules = ${JSON.stringify(bybitRules, null, 2)} as const;

export type BybitFuturesRule = {
	pair: string;
	baseAsset: string;
	quoteCurrency: string;
	minQuantity: number;
	stepSize: number;
	minNotional: number;
};

export type BybitFuturesRules = typeof bybitFuturesRules;
`;

	// Write to file in the same directory
	const filePath = path.join(__dirname, "bybitFuturesRulesData.ts");
	fs.writeFileSync(filePath, tsContent, "utf8");

	console.log(`✅ Bybit futures trading rules written to ${filePath}`);
	console.log(`Total rules: ${bybitRules.length}`);
})();
