import axios from "axios";
import * as fs from "fs";
import * as path from "path";

(async () => {
	const res = await axios.get("https://api.bybit.com/v5/market/instruments-info?category=spot");
	const bybitData = res.data.result.list.map((symbol: any) => {
		return {
			baseCoin: symbol.baseCoin,
			quoteCoin: symbol.quoteCoin,
			status: symbol.status,
			symbol: symbol.symbol,
		};
	});

	// Create TypeScript file content
	const tsContent = `// Auto-generated Bybit exchange data
export const bybitExchangeData = ${JSON.stringify(bybitData, null, 2)} as const;

export type BybitSymbol = {
	baseCoin: string;
	quoteCoin: string;
	status: string;
	symbol: string;
};

export type BybitExchangeData = typeof bybitExchangeData;
`;

	// Write to file in the same directory
	const filePath = path.join(__dirname, "bybitExchangeData.ts");
	fs.writeFileSync(filePath, tsContent, "utf8");

	console.log(`Bybit data written to ${filePath}`);
	console.log(`Total symbols: ${bybitData.length}`);
})();
