name: Docker Build, Test, and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
        env:
          AWS_DEFAULT_REGION: us-east-1  # Replace with your AWS region
          AWS_ACCOUNT_ID: YOUR_AWS_ACCOUNT_ID  # Replace with your AWS account ID

      - name: Build and Tag Docker Image
        run: |
          docker build -t my-docker-image:latest .
        working-directory: ./path/to/Dockerfile/directory

      - name: Test Application
        run: |
          # Add your testing commands here
          # For example, if you're using npm:
          # npm install
          # npm test
        working-directory: ./path/to/tests/directory  # Specify the directory containing your tests

      - name: Push Docker Image to ECR
        run: |
          docker tag my-docker-image:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/my-ecr-repo:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/my-ecr-repo:latest
        env:
          AWS_DEFAULT_REGION: us-east-1  # Replace with your AWS region
          AWS_ACCOUNT_ID: YOUR_AWS_ACCOUNT_ID  # Replace with your AWS account ID
